# Generated by Django 5.2.7 on 2025-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mphone_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='MPhone Id'),
        ),
    ]
