# Generated by Django 5.0.6 on 2025-04-01 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='requested', max_length=25, verbose_name='Статус')),
                ('approver', models.ForeignKey(blank=True, limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvers', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил/Отклонил')),
                ('requester', models.ForeignKey(blank=True, limit_choices_to={'role': ['Cashier', 'Moderator', 'Admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requesters', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'abstract': False,
            },
            bases=('transactions.transaction',),
        ),
    ]
